with TRUCKS AS (
    select CAR.CAR_TYPE, CAR.DAILY_FEE, CAR.CAR_ID, H.HISTORY_ID, DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DAYS,
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN '7일 이상'
        ELSE 'None'
    END
    AS DURATION_TYPE
    from CAR_RENTAL_COMPANY_CAR CAR
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON CAR.CAR_ID = H.CAR_ID
    WHERE CAR.CAR_TYPE = '트럭'
)
# select * from trucks;


select T.HISTORY_ID, 
    ROUND(T.daily_fee * T.DAYS * 
          (100 - IFNULL(PLAN.discount_rate,0)) / 100) AS FEE
from trucks T
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
on T.DURATION_TYPE = PLAN.DURATION_TYPE AND T.CAR_TYPE = PLAN.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
;
